Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore: 
        Location: <S3バケット名>
        Type: S3
      RoleArn: <必須>
      Stages:
        - Name: <必須>
          Actions:
            - 
      Triggers:
        - 
    